''' runner.py is like phone case if phone falls case protects phone , just like that if any error occurs
runner.py tries to fix if not it stores the cause of error for later fixex '''

# importing nessary modules
import subprocess
from sys import stdout
import os
from pathlib import Path
import sys
import traceback

# adding progresion bar
from tqdm import tqdm
import time

# 1. Setup Folder Paths
# import all folder path from config file
from voice_input.Keys.config import output_location, script_location, logs_location, free_cad_cmd, ai_gen_script, ai_gen_folder

# 2. the checker (make sure that output and logs folder exists)
mandatory_path = [output_location, logs_location]
for folder in mandatory_path:
    if not folder.exists():
        print(f"[Runner] Creating folder: {folder}")
        folder.mkdir(parents = True, exist_ok = True)

# a defense mechanisim for not creating an invalid code by ai
import ast

# creating a defensive mechanism
def defense_wall(script_path):
    # reading the generated script
    with open(script_path, "r") as file:
        lines = file.readlines()
    
    cleaned_lines = []
    forbidden = [".remove(","ActiveDocument.removeObject","del "]
    # checking for forbidden words
    for line in lines:
        # check for forbidden
        if any(key in line for key in forbidden):
            continue
        # FIXED: removed "if line.strip()" gate — blank lines matter for code structure
        cleaned_lines.append(line.rstrip())

    full_code = "\n".join(cleaned_lines)
    
    # overriding the code with cleaned code
    with open(script_path,"w")as file:
        file.write(full_code)
    
    # checking for syntax error
    try:
        # if syntax is correct it returns True
        ast.parse(full_code)
        return True 
    except SyntaxError as e:
        # if syntax is wrong it returns False
        print(f"Syntax Error is generated by script:{e}")
        with open(logs_location / "error.report.txt","w") as file:
            file.write(f"syntax_error:{e}")
        return False

# adding helper for correction function
# helper 1
def correction_runner(script_path):
    # calling the correction function
    return subprocess.run(
        [free_cad_cmd, str(script_path)],
        capture_output = True,
        text = True,
        timeout = 20
    )

# this checks if the script suceeeded or not and returns True or False
# like checks if script runner without error
# NOTE: freecad sometimes puts errors in stdout instead of stderr, so we check both
# helper 2
def script_verifier(result):
    return(
        result.returncode == 0
        and "Exception" not in result.stderr
        and "Error" not in result.stderr
        and "Exception" not in result.stdout
        and "Error" not in result.stdout
    )

# helper 3
# this does is checks whichever stream (stderr or stdout) actually has the error message
def error_catcher(result):
    if result.stderr and result.stderr.strip():
        return result.stderr
    if result.stdout and result.stdout.strip():
        return result.stdout
    return "Unknown Error"

# 3. the executor (runns all the function)
def execute_cad_scripts(script_name,user_request):

    # i used import here to prevent 2 files fighting for access
    from voice_input.command_bridge import self_corrector
    
    # mentioning script path
    script_path_use = ai_gen_folder / script_name
    print(f"Running Script:",(script_name))
    
    # we define this so every part of code can access / see this
    log_report = logs_location / "error.report.txt"

    # initialising log manager
    correction_log = logs_location / "correction.log.txt"

    # calling defensive wall to check the code
    if not defense_wall(script_path_use):
        print("Script is invalid")
        # entering log
        with open(logs_location / "error.report.txt", "a")as file:
            file.write(f"Syntax_Error in {script_name}\n")
            file.write(traceback.format_exc())
        return False

    # initializing bar format
    bar_format = "|{bar}| {percentage:3.0f}% {n_fmt}/{total_fmt} [{elapsed}<{remaining}]"

    # mentioning stages
    stages = [
        ("Location"),
        ("Defense Wall"),
        ("Engine"),
        ("Final Progression")
    ]

    # adding progresion bar and desc is decription
    with tqdm (total = len(stages), desc = "Cad Assist in Progress", bar_format = bar_format) as progress_bar:
        # initialising the progresion bar and stages
        for name in stages:
            progress_bar.set_postfix_str(f"Stage:{name}")

            # simulate work progression (slow things so human can see the progression bar)
            time.sleep(0.5)

            # update the progression
            progress_bar.update(1)

    try:
        # we try to run and capture the outcome of this
        result = correction_runner(script_path_use)

        # if script finished without error it prints sucess 
        if script_verifier(result):
            print(f"Script Sucessfully Executed \n Script:{script_name}")
            print("Log:\n",result.stdout) # this prints what script printed
            with open(log_report, "w") as file:
                file.write("Last Run:\n")
                file.write(result.stdout)

            # save code to memory if the code actually works
            from voice_input import stage_manager
            stage_context = open(script_path_use).read()
            stage_manager.script_saver(script_name, stage_context, user_request)

        else:
            # if failed we notify and store info in logs
            print(f"Failed \nCrash Script:{script_name}")
            print(f"Error Detected")

            # -------- self correction loop ----------
            # fixing the broken script
            max_attempts = 3
            fixed = False

            # catch
            error_message = error_catcher(result)

            # log error noting
            with open(correction_log,"a")as file:
                file.write(f"\n{'='*50}\n")
                file.write(f"USER REQUEST: {user_request}\n")
                file.write(f"SCRIPT: {script_name}\n")
                file.write(f"ORIGINAL ERROR:\n{error_message}\n")

            # initialising the loop
            for attempt in range(1, max_attempts + 1):
                print(f"Self Correction Triggered\nAttempt {attempt}/{max_attempts}")
                try:
                    new_code = self_corrector(script_path_use, error_message)
                except Exception as e:
                    print(f"Self correction unavailable: {e}")
                    with open(correction_log, "a") as file:
                        file.write(f"\nSELF CORRECTION UNAVAILABLE:\n{e}\n")
                    break
                with open(script_path_use,"w") as file:
                    file.write(new_code)
                print("Code Successfully Corrected")

                # saving log of correction
                with open(correction_log,"a")as file:
                    file.write(f"\nATTEMPT {attempt} - FIXED CODE:\n{new_code}\n")
                    file.write(f"Applied Fix:\n{new_code}\n")

                # running defence wall
                defense_wall(script_path_use)
                retry_result = correction_runner(script_path_use)
                if script_verifier(retry_result):
                    print("Code fixed successfully")
                    # logging
                    with open(correction_log, "a") as file:
                        file.write("PASS\n══════════════════════════\n")
                    # exit loop
                    fixed = True

                    # saving working code (not buggy codes)
                    from voice_input import stage_manager
                    stage_context = open(script_path_use).read()
                    stage_manager.script_saver(script_name, stage_context, user_request)
                    # end log
                    break
                else:
                    print("Correction did not work")
                    # log the new error
                    with open(correction_log,"a")as file:
                        file.write("Result:Still Failing\n")
                        file.write(f"FAILED CODE:\n{new_code}\n")

                    error_message = error_catcher(retry_result)

            if not fixed:
                print("Failed to fix script after max attempts")
                # log the error again 
                with open(correction_log,"a")as file:
                    file.write(f"Final Result:{max_attempts} attempts failed\n")
                    
            # execute again
            print("Self Correction Is Made, Rerunning the code")
            
            # we have to create (if not exists) and write error report
            with open (log_report,"w") as file:
                file.write("qwen 2.5 crash report\n")
                file.write(f"Stdout:{result.stdout}\n")
                file.write(f"Stderr:{result.stderr}\n")
            print(f"Error Details Are Stored in ", {log_report})

    except subprocess.TimeoutExpired:
        # this part gonna catch the time breaker even
        print(f"Time Exceeded! Script took too long to run Perphaps Long infinte loop? \nUsed Script:{script_name}")
        # entering error in log 
        with open(log_report,"w") as file:
            file.write("Error: Execution Time Exceeded")
        print(f"Time_Out Details Stored in:{log_report}")
    
# 4. test run of runner.py
if __name__ == "__main__":
    # FIX: execute_cad_scripts requires TWO args: script_name + user_request
    execute_cad_scripts("ai_gen_script.py", "test run")
    
