''' this is the model code generated by me , soon ai may use it as refference and write code based on this style '''
# this script creates a box and saves it as .step_file

# accessing Freecad Software bulid-in py-terminal of cad


# importing all dependencies
import FreeCAD # type: ignore
import Part # handles all the geometric operations # type: ignore

# 1.create a document
doc = FreeCAD.newDocument("Version_1")

#2. making a 3d object - box / cube
# making a cube (mentioning all diminsions in mm)
box = Part.makeBox(10,20,30)

# 3.adding shape to the document
# freecad needs like 3d objects / model should be attached to document (for saving , later use etc..)
part = doc.addObject("Part::Feature", "Version_1")
part.Shape = box

# saving it as .step file 
# .step file is universal 3d model works in all software
from pathlib import Path
_output_dir = Path(__file__).resolve().parent.parent / "output"
_output_dir.mkdir(parents=True, exist_ok=True)
output_path = str(_output_dir / "box.step")
part.Shape.exportStep(output_path)

print("Sucess!, Saved to",output_path)